Mail template
lithekod/emails pull request #1
Opened 2021-01-18 11:04 UTC by sornas

Det vore bra om våra utskick var enhetliga och ser någorlunda lika ut varje gång. Framförallt har den här inte en `<ul>` som det senaste mailet hade.

2021-01-18 11:50 UTC, th3tard1sparadox requested changes

2021-01-18 11:50 UTC, th3tard1sparadox commented on template.html
> +    If you don't want any more information from us, <a
```suggestion
    If you don't want any more information mailings from us, <a
```

2021-01-18 12:39 UTC, sornas commented on template.html
> +    If you don't want any more information from us, <a
Bara "mailings" istället för "information mailings"? Jag vet inte om jag hört just "information mailings" förut.

2021-01-18 14:50 UTC, EMattfolk commented on template.html
> +    If you don't want any more information from us, <a
Jag skulle nog bara skriva "any more emails"

2021-01-18 14:51 UTC, EMattfolk approved these changes
Ser bra ut! Vi får fixa lite med css sen också så blir det nog snyggt.

2021-01-18 14:52 UTC, th3tard1sparadox commented on template.html
> +    If you don't want any more information from us, <a
tror "emails" inte riktigt stämmer då de fortfarande får andra typer av mail

2021-01-18 16:10 UTC, sornas commented on template.html
> +    If you don't want any more information from us, <a
> då de fortfarande får andra typer av mail
Inte av oss väl?

2021-01-19 10:04 UTC, th3tard1sparadox approved these changes
Ser bra ut

2021-01-19 10:28 UTC, merged