first draft march 21
lithekod/emails pull request #3
Opened 2021-03-20 19:05 UTC by FredTheDino

Ett första utkast, kolla gärna datumen en extra gång! Så pinsamt när man skriver fel.

2021-03-21 10:59 UTC, EMattfolk reviewed
Ser bra ut. När skulle det skickas?

2021-03-21 10:59 UTC, EMattfolk commented on 21-vt/210330.tpl
> +som vi vill att alla ska va del av!
```suggestion
Nu när tentorna (förhoppningsvis) är över och tentastressen förlorat sitt övertag
är det givetvis dags för fler event med LiTHekod! Våren tar med sig både gamejam och förändringar
som vi vill att alla ska vara del av!
```

2021-03-21 10:59 UTC, EMattfolk commented on 21-vt/210330.tpl
> +Liksom många föreningar, så har COVID gjort det svårt att värva nya styrelsemedlemmar.
```suggestion
Likt många föreningar, så har COVID gjort det svårt att värva nya styrelsemedlemmar.
```
Jag antar att du medvetet skrivit "så", men jag blir ledsen när jag läser det. Hur formella ska vi vara egentligen?

2021-03-21 10:59 UTC, EMattfolk commented on 21-vt/210330.tpl
> +Om man är intresserad av vad dom olika roliga rollerna gör, finns mer information
```suggestion
Typiskt bra att sätta på CV:t och ett tillfälle att få vara del av något större!
Om man är intresserad av vad de olika roliga rollerna gör, finns mer information
```

2021-03-21 10:59 UTC, EMattfolk commented on 21-vt/210330.tpl
> +inte bjuda på dom i person, men Minecraft har inte COVID restriktioner (än).
```suggestion
Givetvis kan inte föreningsåret sluta utan fyrverkerier! Tyvärr kan vi
inte bjuda på fyrverkerier i person, men Minecraft har inte COVID restriktioner (än).
```

2021-03-21 10:59 UTC, EMattfolk commented on 21-vt/210330.tpl
> +GameJams innebär att man på en helg gör ett spel. Under tidigare jams har spel gjorts
```suggestion
GameJams innebär att man gör ett spel på en helg. Under tidigare jams har spel gjorts
```

2021-03-21 10:59 UTC, EMattfolk commented on 21-vt/210330.tpl
> +i välkända spelmotorer så som Unity, Unreal, Excel, Git och verkligheten. Om man är intresserad
```suggestion
i välkända spelmotorer så som Unity, Godot, Excel, Git och verkligheten. Om man är intresserad
```
Har någon faktiskt gjort spel i unreal?

2021-03-21 10:59 UTC, EMattfolk commented on 21-vt/210330.tpl
> +är det ett jättebra tillefälle att bli introducerad till verktyg tekniker och idéer.
```suggestion
är det ett jättebra tillefälle att bli introducerad till verktyg, tekniker och idéer.
```

2021-03-21 14:22 UTC, sornas reviewed
Det saknas lite engelska och så bara.

2021-03-21 14:22 UTC, sornas commented on 21-vt/210330.tpl
> +är det givetvis dags för LiTHekod! Våren tar med sig både gamejam och förändringa
```suggestion
är det givetvis dags för LiTHe kod! Våren tar med sig både game jam och förändringa
```

2021-03-21 14:22 UTC, sornas commented on 21-vt/210330.tpl
> +Liksom många föreningar, så har COVID gjort det svårt att värva nya styrelsemedlemmar.
"Som för många andra föreningar har COVID gjort det svårt att värva nya styrelsemedlemmar."

2021-03-21 14:22 UTC, sornas commented on 21-vt/210330.tpl
> +Intresseanmälan är inte bindande, och tar ungefär 30 sekunder att fylla i.
```suggestion
Vi har ett <a href="https://forms.gle/kSiz6EsvP6dteDQ99">formulär uppe för intresseanmälan</a>.
Intresseanmälan är inte bindande och tar ungefär 30 sekunder att fylla i.
```

2021-03-21 14:22 UTC, sornas commented on 21-vt/210330.tpl
> +Intresseanmälan är inte bindande, och tar ungefär 30 sekunder att fylla i.
Min nya grej är länkar som görs längre så det är tydligare vad de pekar på om de plockas ur sitt sammanhang.

2021-03-21 14:22 UTC, sornas commented on 21-vt/210330.tpl
> +<a href="">här</a>. Anmälan stänger den 1 maj.
```suggestion
Om man är intresserad av vad dom olika roliga rollerna gör finns
<a href="https://lithekod.se/contact/se/"> mer information på vår hemsida</a>.
Anmälan stänger den 1 maj.
```

2021-03-21 14:22 UTC, sornas commented on 21-vt/210330.tpl
> +inte bjuda på dom i person, men Minecraft har inte COVID restriktioner (än).
```suggestion
inte bjuda på dom fysiskt, men Minecraft har inte COVID restriktioner (än).
```

2021-03-21 14:22 UTC, sornas commented on 21-vt/210330.tpl
> +vinna priser och hänga!
```suggestion
LiTHe kod bjuder därför in till en samling tävlingar i Minecraft; en chans att
vinna priser och hänga!
```

2021-03-21 14:22 UTC, sornas commented on 21-vt/210330.tpl
> +<a href="https://discord.gg/su2nSneFyZ">LiTHekods-discordserver</a> och
```suggestion
<a href="https://discord.gg/su2nSneFyZ">LiTHe kods discordserver</a> och
```

2021-03-21 14:22 UTC, sornas commented on 21-vt/210330.tpl
> +nalkas!
```suggestion
har misslyckats. I LiTHe kod vet man dock vad detta betyder: Swedish Coding Cup
nalkas!
```

2021-03-21 14:22 UTC, sornas commented on 21-vt/210330.tpl
> +ypperligt tillfälle att vässa ens CV och plocka upp några fler algoritmer.
```suggestion
ypperligt tillfälle att vässa ens CV och lära sig några fler algoritmer.
```

2021-03-21 14:22 UTC, sornas commented on 21-vt/210330.tpl
> +att hållas i <a href="https://discord.gg/KAuYzbmYrh">LiU GameJams-discordserver</a>!
```suggestion
:POINT: Spring Game Jam - 7-9 maj
Även folk som inte har byxor är välkomna på detta jam! Ett distansjam som kommer
att hållas i <a href="https://discord.gg/KAuYzbmYrh">LiU Game Jams discordserver</a>!
```

2021-03-21 14:22 UTC, sornas commented on 21-vt/210330.tpl
> +GameJams innebär att man på en helg gör ett spel. Under tidigare jams har spel gjorts
```suggestion
Ett game jam innebär att man på en helg gör ett spel. Under tidigare jams har spel gjorts
```

2021-03-21 14:22 UTC, sornas commented on 21-vt/210330.tpl
> +snackas.
```suggestion
Efter många års game jam:ande (ja, det är ett ord) kan ett nytt sorts
event skapas! LiU Game Jam och LiTHe kod bjuder in till === ROLIGT NAMN === där obskyra
game jam-spel tävlas i. Poäng ska samlas, motståndare ska krossas och skit ska
snackas.
```

2021-03-21 14:25 UTC, sornas commented on 21-vt/210330.tpl
> +är det ett jättebra tillefälle att bli introducerad till verktyg tekniker och idéer.
```suggestion
är det ett jättebra tillfälle att bli introducerad till verktyg tekniker och idéer.
```

2021-03-25 12:02 UTC, sornas commented on 21-vt/210330.tpl
> +:POINT: LiTHekodstyrelse 21/22
```suggestion
:POINT: LiTHe kods styrelse 21/22
```

2021-03-28 13:06 UTC, th3tard1sparadox requested changes

2021-03-28 13:06 UTC, th3tard1sparadox commented on 21-vt/210330.tpl
> +:POINT: Något roligt namn
Syltprovning

2021-03-28 13:06 UTC, th3tard1sparadox commented on 21-vt/210330.tpl
> +Kom 20/4 till === PLATS === så kör vi!
LiU Game Jam discorden

2021-03-28 13:06 UTC, th3tard1sparadox commented on 21-vt/210330.tpl
> +Kom 20/4 till === PLATS === så kör vi!
Ha med tid också (17:15-21:00)

2021-03-28 13:06 UTC, th3tard1sparadox commented on 21-vt/210330.tpl
> +event skapas! LiU Game Jam och LiTHe kod bjuder in till === ROLIGT NAMN === där obskyra
```suggestion
Efter många års Game Jam:ande (ja, det är så det heter) är det dags för ett nytt sorts
event! LiU Game Jam och LiTHe kod bjuder in till === ROLIGT NAMN === där obskyra
```

2021-03-28 13:06 UTC, th3tard1sparadox commented on 21-vt/210330.tpl
> +game jam-spel tävlas i. Poäng ska samlas, motståndare ska krossas och skit ska
```suggestion
event skapas! LiU Game Jam och LiTHe kod bjuder in alla till Syltprovning där vi kommer tävla i obskyra
Game Jam-spel. Poäng ska samlas, motståndare ska krossas och skit ska
```

2021-03-28 13:06 UTC, th3tard1sparadox commented on 21-vt/210330.tpl
> +Ett game jam innebär att man gör ett spel på en helg. Under tidigare jams har
```suggestion
Ett Game Jam innebär att man gör ett spel på en helg. Under tidigare jams har
```

2021-03-28 17:57 UTC, sornas commented on 21-vt/210330.tpl
> +gamejams and change that we want everyone to be a part of!
```suggestion
Now when the exams (hopefully) are over and the exam angst has lost its grip,
it is of course time for more events with LiTHe kod! This spring brings both
game jams and changes that we want everyone to be a part of!
```

2021-03-28 17:57 UTC, sornas commented on 21-vt/210330.tpl
> +<a href="https://forms.gle/kSiz6EsvP6dteDQ99">formulär uppe för intresseanmälan</a>.
```suggestion
Like many other organizations, LiTHe kod has had trouble finding a board for 21/22.
If you are intrested, take 30 seconds to fill out <a href="https://forms.gle/kSiz6EsvP6dteDQ99">our interest form</a>.
```

2021-03-28 17:57 UTC, sornas commented on 21-vt/210330.tpl
> +It's great to have on your CV, and is a great possibility to learn and grow as a person.
```suggestion
It's great to have on your CV and a perfect opportunity to learn and grow as a person.
```

2021-03-28 17:57 UTC, sornas commented on 21-vt/210330.tpl
> +but Minecraft doesn't have COVID restrictions (yet).
```suggestion
:POINT: Minecraft Triathlon
The term can't end without fireworks! Unfortunately we can't shoot them in person,
but Minecraft doesn't have COVID restrictions (yet).
```

2021-03-28 17:57 UTC, sornas commented on 21-vt/210330.tpl
> +a chance to win prices and hang out!
```suggestion
LiTHe kod would love to invite you to a collection of Minecraft competitions with
a chance to win prices and hang out!
```

2021-03-28 17:57 UTC, sornas commented on 21-vt/210330.tpl
> +<em>everyone</em> is warmly welcome!
```suggestion
The competitions will be held the 27th of April at 5 PM
in <a href="https://discord.gg/su2nSneFyZ">LiTHe kod's Discord server</a> and
<em>everyone</em> is welcome!
```

2021-03-28 17:57 UTC, sornas commented on 21-vt/210330.tpl
> +to sharpen your CV so sharp it will fall out of the envelop.
```suggestion
On the 10th of April LiU will be hosting a qualification for Swedish Coding Cup (SCC),
the Swedish championship in competitive programming! Make your CV so sharp it will fall out of the envelope.
```

2021-03-28 17:57 UTC, sornas commented on 21-vt/210330.tpl
> +<a href="mail://vordf@lithekod.se">vordf@lithekod.se</a>.
Även om jag gillar mail är jag rätt säker på att vi inte kommer ha någon anmälan. Det är bara att dyka upp och vara med. Jag kan kolla med han grabben.

2021-03-28 17:57 UTC, sornas commented on 21-vt/210330.tpl
> +be held in <a href="https://discord.gg/KAuYzbmYrh">LiU Game Jams discordserver</a>!
```suggestion
Pants are no requirement for this jam! A distance jam that will
be held in <a href="https://discord.gg/KAuYzbmYrh">LiU Game Jam's Discord server</a>!
```

2021-03-28 17:57 UTC, sornas commented on 21-vt/210330.tpl
> +everybody has something to contribute with!
```suggestion
A game jam is an event where you make a game over a weekend. For previous jams
games have been made in well known engines like Unity, Unreal, Godot, Excel, Git and
reality. If you're the least bit interested this is an opportune moment
to get introduced to new tools, techniques and ideas. There is absolutely no
requirement to have won a programming championship to be able to participate,
everybody has something to contribute with!
```

2021-03-28 17:57 UTC, sornas commented on 21-vt/210330.tpl
> +opponents to crush and fun to be had.
```suggestion
After many years of intense jamming, it's time for a new kind of fun!
LiU Game Jam and LiTHe kod are inviting everybody to compete in
obscure and strange game jam games! There are points to collect,
opponents to crush and fun to be had.
```

2021-03-28 17:57 UTC, sornas commented on 21-vt/210330.tpl
> +Come 20/4 17:15 to <a href="https://discord.gg/KAuYzbmYrh">LiU Game Jams discordserver</a> and lets go!
```suggestion
Come 20/4 17:15 to <a href="https://discord.gg/KAuYzbmYrh">LiU Game Jam's Discord server</a> and let's go!
```

2021-03-28 19:26 UTC, FredTheDino commented on 21-vt/210330.tpl
> +Om man är intresserad av vad dom olika roliga rollerna gör, finns mer information
dom is valid!

2021-03-28 19:26 UTC, FredTheDino commented on 21-vt/210330.tpl
> +<a href="mail://vordf@lithekod.se">vordf@lithekod.se</a>.
Då är det ju bara att fixa! Och skriva det här istället!

2021-03-29 15:50 UTC, th3tard1sparadox requested changes
pls fix before send

2021-03-29 15:50 UTC, th3tard1sparadox commented on 21-vt/210330.tpl
> +motståndare ska krossas och skit ska snackas.
```suggestion
vi kommer tävla i obskyra game jam-spel. Motståndare ska krossas och skit ska snackas.
```

2021-03-29 15:50 UTC, th3tard1sparadox commented on 21-vt/210330.tpl
> +opponents to crush and fun to be had.
```suggestion
obscure and strange game jam games! There are opponents to crush and fun to be had.
```

2021-03-29 18:12 UTC, merged